apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    tier: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30124
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: adryeh/diplom:back1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
