"""empty message

Revision ID: 255cacc1a938
Revises: 5a763f8eb910
Create Date: 2021-06-08 03:21:21.326314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255cacc1a938'
down_revision = '5a763f8eb910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('skill_progress', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employee', sa.Column('web_site', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('github', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('facebook', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'facebook')
    op.drop_column('employee', 'github')
    op.drop_column('employee', 'web_site')
    op.drop_table('employee_skill')
    # ### end Alembic commands ###
