"""empty message

Revision ID: 2cb9a21680d6
Revises: 6666c0ff6b80
Create Date: 2021-06-04 00:36:17.759248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb9a21680d6'
down_revision = '6666c0ff6b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('location', sa.String(), nullable=True))
    op.add_column('company', sa.Column('number_of_employees', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('education', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('citizenship', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('employee', 'citizenship')
    op.drop_column('employee', 'age')
    op.drop_column('employee', 'gender')
    op.drop_column('employee', 'education')
    op.drop_column('company', 'number_of_employees')
    op.drop_column('company', 'location')
    op.drop_table('vacancy')
    op.drop_table('cv')
    # ### end Alembic commands ###
