"""empty message

Revision ID: 5a763f8eb910
Revises: 2cb9a21680d6
Create Date: 2021-06-07 01:41:41.638299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a763f8eb910'
down_revision = '2cb9a21680d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'position')
    # ### end Alembic commands ###
