"""empty message

Revision ID: df8fa844f473
Revises: 255cacc1a938
Create Date: 2021-06-09 03:06:36.669291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8fa844f473'
down_revision = '255cacc1a938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'about')
    # ### end Alembic commands ###
